import Head from "next/head";
import { Inter } from "@next/font/google";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import WhatIdo from "../components/WhatIdo"
import Footer from "../components/Footer";
import { useState } from "react";
import Sidebar from "../components/Sidebar";
import About from "./about";
import Contact from "./contact";
import Project from "./project";
import Skill from "./skills";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const toggleSidebar = () => {
    setIsOpen(!isOpen)
  }
  return (
    <>
      <Head>
        <title>Mohammad Adnan | Portfolio</title>
        <meta name="description" content="Generated by nextjs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Navbar toggleSidebar={toggleSidebar}/>
      </header>
    
      <main>
        
        <Sidebar isOpen={isOpen} toggleSidebar={toggleSidebar}/>
        <Hero />
        <About/>
        <WhatIdo/>
        <Skill/>
        <Project/>
        <Contact/>
        
        
      </main>
      <footer>
        <Footer/>
      </footer>
    </>
  );
}
